# Config file for automatic testing at travis-ci.org

sudo: required

#language: python

#python:
#  - "3.4"
#  - "2.7"
#  - "pypy"

services:
  - docker

before_install:
  - docker build -t quantopian/zipline https://github.com/quantopian/zipline.git#1.0.2
  - docker-compose -f docker-compose-test.yml up

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
#install: pip install -r requirements/test.txt

# command to run tests, e.g. python setup.py test
#script: python setup.py test
script:
  - travis_wait 40 docker-compose -f docker-compose-test.yml run --rm stockbot tox -e py27
  - travis_wait 40 docker-compose -f docker-compose-test.yml run --rm stockbot tox -e py34
