# Config file for automatic testing at travis-ci.org

sudo: required

services:
  - docker

before_install:
  - docker build -t quantopian/zipline https://github.com/quantopian/zipline.git
  - docker-compose -f docker-compose-test.yml create

script:
  - >
    travis_wait 40
    docker-compose -f docker-compose-test.yml run --rm stockbot
    tox -e py27
  - >
    travis_wait 40
    docker-compose -f docker-compose-test.yml run --rm stockbot
    tox -e py35
