version: '2'

volumes:
  zipline_data: {}

services:
  stockbot:
    build:
      context: .
      dockerfile: ./compose/stockbot/Dockerfile
    image: cpappalardo/stockbot
    volumes:
      - zipline_data:/root/.zipline
