version: '2'

volumes:
  zipline_data_dev: {}

services:
  stockbot:
    build:
      context: .
      dockerfile: ./compose/stockbot/Dockerfile-dev
    image: cpappalardo/stockbot:dev
    volumes:
      - .:/app
      - zipline_data_dev:/root/.zipline
