
FROM quantopian/zipline
ENV PYTHONUNBUFFERED 1
ENV DEBIAN_FRONTEND noninteractive
ENV TERM xterm

# update, upgrade, and install packages (including nodejs 0.12.x)
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y apt-utils \
    && apt-get install -y nano less make

# configure apt-utils (fixes warnings)
RUN dpkg-reconfigure apt-utils

# upgrade pip
RUN pip install --upgrade pip

# set some useful defaults
RUN echo "alias ls='ls --color'" >> /etc/bash.bashrc
RUN echo "alias grep='grep --color=auto'" >> /etc/bash.bashrc

# install package and requirements (editable for development)
COPY . /app
RUN pip install -r /app/requirements/dev.txt
RUN pip install -e /app

# stage the entrypoint
COPY ./compose/stockbot/entrypoint-dev.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]
